### ISSUE TITLE
Camera permission error in embedded pads

### ISSUE THREAD

**Issue by KepaUrzelai** [ether/ep_webrtc#102]
Hello,

First of all, congratulations for this great plugin! It fits perfectly with the idea of collaborative pads of Etherpad-lite.

In the service that I've installed, everything works as expected. The problem comes when integrating Etherpad-lite to Moodle.
With Webrtc video/voice chat disabled, nothing goes wrong, but if I enable that, the following error is shown: _"Sorry, you need to give us permission to use your camera and microphone."_

I have ensured that both Moodle and Etherpad have Video and Voice permissions through the browser configuration.

Isn't it possible to use webrtc also in the pads that are embedded and accessed through the API?

For more information, here is the Moodle plugin that allows the integration: [mod_etherpadlite](https://github.com/moodlehu/moodle-mod_etherpadlite)

Thank you for your help.

Kepa

**Comment by rhansen** [comment]
This plugin has changed a lot since you opened the bug. Please try the latest version.

**Comment by lisandi** [comment]
Thanks @KepaUrzelai and I am happy to verify that problem - we have the same problem in HumHub - 
![Screen Shot 2021-09-23 at 00 45 31](https://user-images.githubusercontent.com/1982011/134396209-45dc216e-3d44-4b95-afe2-ef74ba6d4ebf.png)
we tested it out also in Safari with the same problem.

**Comment by JohnMcLear** [comment]
@lisandi can you please confirm the version of the plugin you are using?

**Comment by rhansen** [comment]
Also, is the iframe served from the [same origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) as the containing page?

**Comment by lisandi** [comment]
Yes it has HTTPS via Apache Proxy involved.

Etherpad version
Version number: 1.8.14

Latest available version: 1.8.14

Git sha: 571b37b

Installed plugins
ep_auth_session
ep_embedded_hyperlinks2
ep_comments_page
ep_align
ep_etherpad-lite
ep_webrtc
ep_markdown
ep_font_color
ep_headings2
Installed parts
ep_headings2/main
ep_font_color/main
ep_markdown/markdown
ep_webrtc/ep_webrtc
ep_etherpad-lite/openapi
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/stats
ep_etherpad-lite/express
ep_etherpad-lite/Minify
ep_etherpad-lite/DB
ep_align/main
ep_etherpad-lite/webaccess
ep_comments_page/comments_page
ep_etherpad-lite/static
ep_embedded_hyperlinks2/main
ep_auth_session/auth_session
Installed hooks
Server-side hooks
clientVars:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_webrtc:
ep_webrtc:
collectContentPost:
ep_align:
main:
ep_align/static/js/shared
ep_font_color:
main:
ep_font_color/static/js/shared
ep_headings2:
main:
ep_headings2/static/js/shared
collectContentPre:
ep_align:
main:
ep_align/static/js/shared
ep_comments_page:
comments_page:
ep_comments_page/static/js/shared
ep_font_color:
main:
ep_font_color/static/js/shared
ep_headings2:
main:
ep_headings2/static/js/shared
createServer:
ep_etherpad-lite:
express:
ep_etherpad-lite/node/hooks/express
eejsBlock_dd_format:
ep_font_color:
main:
ep_font_color/index
eejsBlock_editbarMenuLeft:
ep_align:
main:
ep_align/index
ep_comments_page:
comments_page:
ep_comments_page/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/index
ep_font_color:
main:
ep_font_color/index
ep_headings2:
main:
ep_headings2/index
eejsBlock_editorContainerBox:
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/index
eejsBlock_exportColumn:
ep_markdown:
markdown:
ep_markdown/index
eejsBlock_mySettings:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_markdown:
markdown:
ep_markdown/index
ep_webrtc:
ep_webrtc:
eejsBlock_scripts:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_markdown:
markdown:
ep_markdown/index
eejsBlock_styles:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_webrtc:
ep_webrtc:
exportEtherpadAdditionalContent:
ep_comments_page:
comments_page:
ep_comments_page/index
exportHTMLAdditionalContent:
ep_comments_page:
comments_page:
ep_comments_page/exportHTML
exportHtmlAdditionalTagsWithData:
ep_comments_page:
comments_page:
ep_comments_page/exportHTML
ep_font_color:
main:
ep_font_color/exportHTML
expressCloseServer:
ep_etherpad-lite:
socketio:
ep_etherpad-lite/node/hooks/express/socketio
expressConfigure:
ep_etherpad-lite:
webaccess:
ep_etherpad-lite/node/hooks/express/webaccess
expressCreateServer:
ep_auth_session:
auth_session:
ep_auth_session/index:registerRoute
ep_comments_page:
comments_page:
ep_comments_page/index
ep_etherpad-lite:
admin:
ep_etherpad-lite/node/hooks/express/admin
adminplugins:
ep_etherpad-lite/node/hooks/express/adminplugins
adminsettings:
ep_etherpad-lite/node/hooks/express/adminsettings
apicalls:
ep_etherpad-lite/node/hooks/express/apicalls
errorhandling:
ep_etherpad-lite/node/hooks/express/errorhandling
i18n:
ep_etherpad-lite/node/hooks/i18n
importexport:
ep_etherpad-lite/node/hooks/express/importexport
openapi:
ep_etherpad-lite/node/hooks/express/openapi
padreadonly:
ep_etherpad-lite/node/hooks/express/padreadonly
padurlsanitize:
ep_etherpad-lite/node/hooks/express/padurlsanitize
socketio:
ep_etherpad-lite/node/hooks/express/socketio
specialpages:
ep_etherpad-lite/node/hooks/express/specialpages
static:
ep_etherpad-lite/node/hooks/express/static
tests:
ep_etherpad-lite/node/hooks/express/tests
ep_markdown:
markdown:
ep_markdown/express
getLineHTMLForExport:
ep_align:
main:
ep_align/index
ep_comments_page:
comments_page:
ep_comments_page/exportHTML
ep_font_color:
main:
ep_font_color/exportHTML
ep_headings2:
main:
ep_headings2/index
handleMessage:
ep_webrtc:
ep_webrtc:
handleMessageSecurity:
ep_comments_page:
comments_page:
ep_comments_page/index
import:
ep_markdown:
markdown:
ep_markdown/index
loadSettings:
ep_webrtc:
ep_webrtc:
padCopy:
ep_comments_page:
comments_page:
ep_comments_page/index
padInitToolbar:
ep_align:
main:
ep_align/index
ep_comments_page:
comments_page:
ep_comments_page/index
ep_font_color:
main:
ep_font_color/index
padRemove:
ep_comments_page:
comments_page:
ep_comments_page/index
restartServer:
ep_etherpad-lite:
express:
ep_etherpad-lite/node/hooks/express
shutdown:
ep_etherpad-lite:
DB:
ep_etherpad-lite/node/db/DB
express:
ep_etherpad-lite/node/hooks/express
Minify:
ep_etherpad-lite/node/utils/Minify
stats:
ep_etherpad-lite/node/stats
socketio:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_etherpad-lite:
adminplugins:
ep_etherpad-lite/node/hooks/express/adminplugins
adminsettings:
ep_etherpad-lite/node/hooks/express/adminsettings
socketio:
ep_etherpad-lite/node/handler/PadMessageHandler
ep_webrtc:
ep_webrtc:
:setSocketIO
stylesForExport:
ep_font_color:
main:
ep_font_color/exportHTML
ep_headings2:
main:
ep_headings2/index
Client-side hooks
aceAttribsToClasses:
ep_align:
main:
ep_align/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
aceCreateDomLine:
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
aceDomLineProcessLineAttributes:
ep_align:
main:
ep_align/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
aceEditEvent:
ep_align:
main:
ep_align/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
aceEditorCSS:
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_markdown:
markdown:
ep_markdown/static/js/markdown
aceInitialized:
ep_align:
main:
ep_align/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
aceRegisterBlockElements:
ep_align:
main:
ep_align/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
collectContentPre:
ep_align:
main:
ep_align/static/js/shared
ep_comments_page:
comments_page:
ep_comments_page/static/js/shared
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/shared
ep_headings2:
main:
ep_headings2/static/js/shared
handleClientMessage_RTC_MESSAGE:
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js
postAceInit:
ep_align:
main:
ep_align/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_markdown:
markdown:
ep_markdown/static/js/markdown
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js
postToolbarInit:
ep_align:
main:
ep_align/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
userJoinOrUpdate:
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js
userLeave:
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js


----
I suggest that you display always the version number behind those used items!
----

webrtc | WebRTC based audio/video chat to Etherpad | 0.1.82

**Comment by rhansen** [comment]
@lisandi Did you see my question about same origin?

**Comment by lisandi** [comment]
The iframe of course is NOT served from the same origin because on the same origin runs the script and can't run the proxy. - Besides that we need to have one etherpad but have multiple access points via proxies.

The site is at https://my.domain (HumHub Installation)
and the pad runs at https://pad.my.domain (Apache Proxy)


If those versions are NOT the newest ones than something is simply wrong on how those plugins get installed as the etherpad had been set up yesterday complete new - so all versions actually should be the newest versions at all no matter if plugin or etherpad itself!

We installed Etherpad via Github and than ran the dependencies install and then installed 
npm install --no-save --legacy-peer-deps ep_headings2 ep_markdown ep_comments_page ep_align ep_font_color ep_webrtc ep_embedded_hyperlinks2
as featured here: https://github.com/ether/etherpad-lite#installation

We tried to install also ep_hash_auth but that was constantly causing a not working etherpad so we did no more install it as it is actually not needed because the admin can be enabled and disabeled via settings.json.

But we realized that we also get 4 moderate and 2 high vulnerabilities showing up as well as that package.json script had been build with Version 2 but here it gets only Version 1 when installing etherpad. - not sure if that's related but like to let you know.

Name | Description | Version |  
-- | -- | -- | --
adminpads2 | Etherpad plugin to list and delete pads in /admin. | 2.1.43 |  
align | Etherpad plugin to set left, center, right, or full justification for a paragraph | 0.3.38 |  
auth_session | Provides a route that authenticates the user with the provided sessionID parameter and redirects to the given padName | 1.1.1 |  
author_neat2 | Etherpad plugin that uses colored underlines instead of colored backgrounds to indicate authorship. | 2.0.1 |  
authorship_toggle | Toggle authorship colors on and off. | 0.0.8 |  
comments_page | Adds comments on sidebar and link it to the text. For no-skin use ep_page_view. | 0.1.69 |  
countable | Displays paragraphs, sentences, words and characters counts. | 0.0.11 |  
dividing_line | insert dividingline | 0.0.2 |  
embedded_hyperlinks2 | Adds hyperlinks to etherpad | 1.2.2 |  
embedmedia | Embed media (youtube, vimeo etc) | 0.0.18 |  
font_color | Apply colors to fonts | 0.0.49 |  
font_family | Add support for different Fonts | 0.5.33 |  
font_size | Apply sizes to fonts | 0.4.28 |  
headings2 | Adds heading support to Etherpad Lite. Includes improved suppot for export, i18n etc. | 0.2.32 |  
line_spacing | Apply line spacing | 1.0.1 |  
markdown | Edit and Export as Markdown in Etherpad | 0.1.39 |  
special_characters | Insert special characters into a pad | 0.0.15 |  
spellcheck | Add support to do 'Spell checking', with a toggle on/off option in Settings | 0.0.32 |  
subscript_and_superscript | Add support for different Fonts | 0.2.33 |  
template_content | Adds the ability to insert pre-defined template content into a pad. | 0.0.10 |  
text_statistics | Reading Ease and Grade Level of a pad | 0.0.11 |  
webrtc | WebRTC based audio/video chat to Etherpad | 0.1.82 |  

<br class="Apple-interchange-newline">

**Comment by rhansen** [comment]
> The iframe of course is NOT served from the same origin because on the same origin runs the script and can't run the proxy. - Besides that we need to have one etherpad but have multiple access points via proxies.

You could reverse proxy Etherpad in a subdirectory (e.g., `/etherpad`) so that it is served from the same origin as your main site.


Another thing to check: Is the [`iframe`'s `allow` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-allow) set to `camera; microphone`? For example:

```html
<iframe src="/etherpad/p/asdf" allow="camera; microphone">
```

**Comment by lisandi** [comment]
<VirtualHost pad.my.domain:80>
  SuexecUserGroup "#1234" "#1234"
  ServerName pad.my.domain

  LoadModule  proxy_module         /usr/lib/apache2/modules/mod_proxy.so
  LoadModule  proxy_http_module    /usr/lib/apache2/modules/mod_proxy_http.so
  LoadModule  headers_module       /usr/lib/apache2/modules/mod_headers.so
  LoadModule  deflate_module       /usr/lib/apache2/modules/mod_deflate.so
 
  ProxyVia On
  ProxyRequests Off
  ProxyPass / http://localhost:9001/
  ProxyPassReverse / http://localhost:9001/
  ProxyPreserveHost on
  <Proxy *>
    Options FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
  </Proxy>
 
#RewriteEngine on
#RewriteCond %{SERVER_NAME} =pad.my.domain
#RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
</VirtualHost>

<VirtualHost pad.my.domain:443>
  SuexecUserGroup "#1234" "#1234"
  ServerName pad.my.domain

  LoadModule  proxy_module         /usr/lib/apache2/modules/mod_proxy.so
  LoadModule  proxy_http_module    /usr/lib/apache2/modules/mod_proxy_http.so
  LoadModule  headers_module       /usr/lib/apache2/modules/mod_headers.so
  LoadModule  deflate_module       /usr/lib/apache2/modules/mod_deflate.so
 
  ProxyVia On
  ProxyRequests Off
  ProxyPass / http://localhost:9001/
  ProxyPassReverse / http://localhost:9001/
  ProxyPreserveHost on
  <Proxy *>
    Options FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
  </Proxy>
 
#RewriteEngine on
#RewriteCond %{SERVER_NAME} =pad.my.domain
#RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]

SSLEngine on
SSLCertificateFile /home/my-user/ssl.cert
SSLCertificateKeyFile /home/my-user/ssl.key
SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLCACertificateFile /home/my-user/ssl.ca

</VirtualHost>

But that can't be actually the problem as when you call the pad on the domain directly it has the same problem! - without iFrame! The image is from https://pad.my.domain and the camera and mic are not working either - in that case it is same origin
![Screen Shot 2021-09-23 at 10 48 01](https://user-images.githubusercontent.com/1982011/134452100-429b8d4e-b60a-48d5-adad-c01317798982.png)

**Comment by lisandi** [comment]
I just checked on the HumHub Installation and here your assumption seems to be right but here the whole pad won't show up!
With Error Message: SecurityError: Blocked a frame with origin "https://pad.phuket.church" from accessing a cross-origin frame. So, in my opinion, it is not related to the camera and microphone problems.
![Screen Shot 2021-09-23 at 11 02 18](https://user-images.githubusercontent.com/1982011/134453051-12c2afad-2d30-4775-b3d2-12d6f2b45c9b.png)

**Comment by lisandi** [comment]
OK working in a subdirectory like that here: The main application in our case is HumHub on Apache2 - Ubuntu 20.04 - Webmin/Virtualmin. The pad works in https://my.domain/pad/ and we had to use HTTPS: https://my.domain/pad/ as URL in HumHub as HTTP: http://my.domain/pad/ won't work as all has to be connected via HTTPS on our server. Of course plus the correct API key. And now the video is also working - You might add that to the WIKI as a configuration for Apache2 on Ubuntu20.04 and Webmin/Virtualmin - or let me know how I can add it.

```
<VirtualHost 12.34.56.78:80>
    SuexecUserGroup #1234 #1234
    ServerName my.domain
    ServerAlias www.my.domain
    DocumentRoot /home/my-user/public_html
    ErrorLog /var/log/virtualmin/my.domain_error_log
    CustomLog /var/log/virtualmin/my.domain_access_log combined
    ScriptAlias /cgi-bin/ /home/my-user/cgi-bin/
    DirectoryIndex index.html index.htm index.php index.php4 index.php5
    <Directory /home/my-user/public_html>
    Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch
    allow from all
    AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
    Require all granted
    </Directory>
    <Directory /home/my-user/cgi-bin>
    allow from all
    AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
    Require all granted
    </Directory>
    RewriteEngine on
    RemoveHandler .php
    RemoveHandler .php7.4
    RemoveHandler .php8.0
<FilesMatch \.php$>
    SetHandler proxy:fcgi://localhost:8009
</FilesMatch>

# Etherpad lite
RewriteEngine On
RewriteRule ^/pad$ /pad/ [R]
ProxyPass /pad/ http://127.0.0.1:9001/
ProxyPassReverse /pad/ http://127.0.0.1:9001/
ProxyPreserveHost on

</VirtualHost>
<VirtualHost 12.34.56.78:443>
    SuexecUserGroup #1234 #1234
    ServerName my.domain
    ServerAlias www.my.domain
    DocumentRoot /home/my-user/public_html
    ErrorLog /var/log/virtualmin/my.domain_error_log
    CustomLog /var/log/virtualmin/my.domain_access_log combined
    ScriptAlias /cgi-bin/ /home/my-user/cgi-bin/
    DirectoryIndex index.html index.htm index.php index.php4 index.php5
    <Directory /home/my-user/public_html>
    Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch
    allow from all
    AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
    Require all granted
    </Directory>
    <Directory /home/my-user/cgi-bin>
    allow from all
    AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
    Require all granted
    </Directory>
    RewriteEngine on
    RemoveHandler .php
    RemoveHandler .php7.4
    RemoveHandler .php8.0
<FilesMatch \.php$>
    SetHandler proxy:fcgi://localhost:8009
</FilesMatch>
SSLEngine on
SSLCertificateFile /home/my-user/ssl.cert
SSLCertificateKeyFile /home/my-user/ssl.key
SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLCACertificateFile /home/my-user/ssl.ca

# Etherpad lite
RewriteEngine On
RewriteRule ^/pad$ /pad/ [R]
ProxyPass /pad/ http://127.0.0.1:9001/
ProxyPassReverse /pad/ http://127.0.0.1:9001/
ProxyPreserveHost on

</VirtualHost>
```

![Screen Shot 2021-09-23 at 12 24 31](https://user-images.githubusercontent.com/1982011/134458379-1cda7f3d-e260-4ed5-b4dd-17ee5ccde45b.png)

**Comment by lisandi** [comment]
Thanks for all your help - Etherpad is really a great tool with a great community!
Issue is Solved!

**Comment by KepaUrzelai** [comment]
Thank you guys for solving this issue!
