### ISSUE TITLE
We should move this project to "ether" organization

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ep_webrtc#25]
As per title, makes sense to get more support in maintaining.

**Comment by bit** [comment]
sure, what needs to be done to do that?

**Comment by JohnMcLear** [comment]
to keep it super simple for you afaik you can make me repo admin

I might need to make you admin on ether/ if not.

**Comment by JohnMcLear** [comment]
Okay that didn't work.

https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/

n GitHub Enterprise, navigate to the main page of the repository.

Repository settings buttonUnder your repository name, click

Settings.

Transfer buttonClick Transfer.
Read the warnings and enter the repository name to confirm that you've done so.
Transfer buttonType the name of the new owner and click I understand, transfer this repo. 

Try follow those steps.  If that doesn't work I will make you admin on ether/ -- I have a feeling I will get an invitation to accept the repo

**Comment by bit** [comment]
I get:
 You don’t have the permission to create public repositories on ether

**Comment by bit** [comment]
moved now.

**Comment by JohnMcLear** [comment]
Excellent thanks :D
