### ISSUE TITLE
Font-size for no camera msg not big enough

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ep_webrtc#30]
Custom css would be fine.

**Comment by orblivion** [comment]
Does the gritter fix this one?

**Comment by JohnMcLear** [comment]
Gritter would make a LOT more sense than what we're currently using.  Good idea!  Please shift everything to gritter!

**Comment by orblivion** [comment]
I'm saying that it's already done. All error messages from `getUserMedia`
are going through gritter.

https://github.com/ether/ep_webrtc/blob/1b836ad1b006d37740c0ff0cdddb49601db1aa1b/static/js/webrtc.js#L142

**Comment by orblivion** [comment]
Try it out! Turn off your camera or deny permission or whatever, you should see the error pop up.

**Comment by JohnMcLear** [comment]
Awesome , this should be perfect!  Nicely done :)

**Comment by orblivion** [comment]
I mean, to be fair it was the other guy who did the gritter part haha
