### ISSUE TITLE
Custom Error msg for camera not available

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ep_webrtc#31]

**Comment by orblivion** [comment]
If I understand this correctly, you want a setting (in etherpad-lite's settings.js) that lets you replace the [existing hard-coded error message](https://github.com/ether/ep_webrtc/blob/591fa66/static/js/webrtc.js#L542)?

**Comment by orblivion** [comment]
And if so, why only this message? (There are three "Sorry"s in that file.)

**Comment by JohnMcLear** [comment]
If I deny camera access I currently get

 "Sorry, you need to install SSL certificates for your Etherpad instance to use WebRTC";

And just freestyle the error msg, "No camera available, make sure your webcam is plugged in" or something

**Comment by orblivion** [comment]
Ah, yes. That initial error message fix I did was incomplete. There are more kinds of errors and at some point I was gonna handle them, so I guess that's what this task is. I think what you're describing may be `AbortError`, I think I noticed it as well.

**Comment by orblivion** [comment]
FYI I switched to this one for a "short break" from the videoTrack.stop security issue and found myself knee deep* in breaking changes in the webRTC spec that's made this take way longer than expected. Good news is that we should have much better error handling after this though. I'll PR soon.

\* (So get this: until recently, `NotAllowedError` either meant SSL error, or user didn't give permission; _exact_ same error. This is why we were testing for `https`, it was the only way of telling them apart. NOW, `NotAllowedError` only means user didn't give permission, and SSL error is handled by `mediaDevices` being absent altogether! Which means now we can't use "`getUserMedia` is missing" as a sign that the browser doesn't support WebRTC. I think I found another way though.)

**Comment by orblivion** [comment]
Should we close this issue?

**Comment by JohnMcLear** [comment]
@orblivion How can I close it?  Is it possible to set a custom message for an error?  If so, how?

**Comment by orblivion** [comment]
Oops, I sort of got distracted by the requisite general fix for error messages (but also your first answer was a bit unclear).

Adding a customization should be quick. Does `settings.json` sound like a good place?

BTW I'm curious why this is the only error message you want to customize?

**Comment by JohnMcLear** [comment]
Yea.  Well I guess exposing customizing any string presented by i18n makes sense?

**Comment by orblivion** [comment]
Sounds good. So the tasks shall be:

* i18nize all of the a/v connection error messages
* Let the user override anything in the i18n json files within settings.json
* Add instructions for the preceding in `README`

**Comment by orblivion** [comment]
(no longer such a quick task, but probably not large)

**Comment by JohnMcLear** [comment]
Yeah consider the admin might only want to override the en_gb string too not the global value.

**Comment by orblivion** [comment]
I'd like to add a test for this but I'm not seeing any existing examples of testing different values in settings.json. Tests seem to just use the current user's settings.json. Is there a path I'm not seeing or would I need to forge a new path?

**Comment by JohnMcLear** [comment]
Is it passed in clientVars?

**Comment by orblivion** [comment]
Didn't see it anywhere in tests. But I figured the right place was in the backend anyway. See PR forthcoming.

**Comment by orblivion** [comment]
Still need #46

**Comment by orblivion** [comment]
Now that we merged https://github.com/ether/etherpad-lite/pull/4000, we can do custom overrides for l10n. However, that doesn't yet include ep_webrtc error messages. For that we need to merge #46. We may want to reopen this issue until it's done.

**Comment by JohnMcLear** [comment]
@orblivion  closable?

**Comment by orblivion** [comment]
Yep!
