### ISSUE TITLE
More log entries or debug log

### ISSUE THREAD

**Issue by ukcb** [ether/ep_webrtc#44]
I would like a log file entry which STUN server (variable: pc_config.iceServers) is really used. Unfortunately, nothing can be found in the log file. Would be nice if you could see it at loglevel INFO or DEBUG. Many thanks!

**Comment by JohnMcLear** [comment]
btw on the client you can do something like

``clientVars.ep_webrtc`` in developer console, and this will tell you :D  That's prolly easier is it not?

**Comment by ukcb** [comment]
Ok, it doesn't have to be in the logs.
