### ISSUE TITLE
Post stats back to the server

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ep_webrtc#45]
Etherpad has a ``stats`` method available, it also has the ability to push error msgs back to the server.

We should grab ep_webrtc errors (with the plugin), post them to the server and then include them in the ``stats`` results.

See https://video.etherpad.com/metrics for how to see stats as graphis
See https://video.etherpad.com/stats for how to see stats

Afaik we would just $.post the error back to a newly exposed endpoint then write the values with.

```
  stats.meter('ep_webrtc_SOME_ERROR').mark();
```

https://www.npmjs.com/package/measured-core is the exposed library

**Comment by JohnMcLear** [comment]
@orblivion can you pick this up plz?

**Comment by orblivion** [comment]
#45

**Comment by orblivion** [comment]
#54

**Comment by JohnMcLear** [comment]
Thanks!
