### ISSUE TITLE
Disable by default makes the server crash.

### ISSUE THREAD

**Issue by julpec** [ether/ep_webrtc#48]
Hello
First, thanks for this plugin, very useful and simple (as usual in etherpad).
I installed the plugin without any problem. It was used earlier with 6 people.
Now, I just tried to disable by default by adding this in my settings.json: 
```
"ep_webrtc" : {
    "enabled" : false
}
```
but after that, my etherpad instance doesn't want to run. I have this error:
```
[2020-05-13 23:09:03.965] [ERROR] console - There was an error processing your settings file from /var/www/etherpad-prive/settings.json: Unexpected string in JSON at position 1865
```

Node: v10.20.1
etherpad: 1.8.3
npm: 6.14.4

**Comment by JohnMcLear** [comment]
This is being rewritten at the moment by @orblivion - we hope to have something land soon :)

**Comment by orblivion** [comment]
This one actually looks like a json format error. Probably that you need a comma before this?

**Comment by orblivion** [comment]
In `settings.json`. I recognize it because I've seen it a lot lately :-)

**Comment by julpec** [comment]
I'm so sorry... 
I worked on this a little late at night and I hadn't actually paid attention to the comma... the shame on me :(
Sorry to have wasted your time.
However, the default disable doesn't work, it keeps asking for permission and enabling video conferencing.

**Comment by orblivion** [comment]
No worries! Glad to help. It's confused me a few times as well.

As far as the feature not working: Did you ever use the "Enable Audio/Video Chat" switch under the settings gearbox? It basically does the same thing, except per-user. If you've ever touched it, it sets a cookie _for that user_ that will override anything you put in `settings.json`. However if you, let's say, try opening the pad in an incognito window, it should respect your `settings.json` until you check the checkbox under the gear.

I hope to have a bit better documentation for this soon in the README.

**Comment by julpec** [comment]
Yes, but this is user related and not pad related, which is a problem for me. I think a pad needs to be configured by its creator and then eventually users can override the pad's configurations.
But I don't think that's the philosophy of etherpad and I'll be happy with this default disabling (which works btw).
The only problem for me is to make users know that they can enable it in the settings (knowing that each user of the pad has to do the action).
