### ISSUE TITLE
If enough people join video, your own video pinned to the top becomes inaccessible and then you can't mute/unmute yourself

### ISSUE THREAD

**Issue by mvolz** [ether/ep_webrtc#49]
We tested this (I think this is the right repo?) at video.etherpad.com and when the screen filled with enough people and scrolling becomes enabled, the video of yourself that's pinned to the top was only variably accessible; sometimes it was missing entirely, sometimes I could only access the bottom. This made it impossible to turn off my mic/camera from the UI. 

I was using chrome, another user in the chat was on a mobile browser and reported the same issue.

**Comment by JohnMcLear** [comment]
Right repo and thanks @seballot any idea on best UI?  @orblivion is looking into adding more content and different options for resizing and I think being mindful of things growing here could be useful! :)

**Comment by seballot** [comment]
Oh indeed, it's a known bug of flex center : https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container#33455342

Will fix
