### ISSUE TITLE
Custom video size (needs css)

### ISSUE THREAD

**Issue by orblivion** [ether/ep_webrtc#52]
There is an issue for some users wherein the video sizes are too small for sign language to come through clearly. There is a proposed solution to make the video size configurable. I've implemented this from the javascript side; the admin simply specifies a number of pixels for "small" and "large" in settings. "large" being after the video is maximized. And width vs height are specified as the same currently in CSS despite the aspect ratio, so I assumed the custom version could continue to do the same.

All that said, it doesn't work past a certain point because there are CSS issues blocking it. If I choose a size of 800, it looks about the same as 400. I'm not a CSS person, so as I mentioned to John before, I'd like to hand this off to @seballot for whenever he has time.

My work can be found here: https://github.com/ether/ep_webrtc/compare/master...orblivion:custom-video-size?expand=1

**Comment by JohnMcLear** [comment]
@seballot I'd appreciate if you can take a glance at this :)  We want to make sure the UX works flawlessly here and UI is going to be a huge part of getting this feature right.

**Comment by seballot** [comment]
Hi !

try using `width` instead of `max-width`, but keep `max-height` as it is

**Comment by orblivion** [comment]
Yeah that seems to do the trick. See #52. But there's still a problem. I'll mention it there.

**Comment by JohnMcLear** [comment]
Is there no way to make the video size "draggable" to resize?  I think that was an ask :)

**Comment by orblivion** [comment]
Sure, but then I should probably rip out this entire change, right?

**Comment by orblivion** [comment]
Or maybe not everyone wants to drag?

**Comment by JohnMcLear** [comment]
Not everyone will want drag, under a flag I guess!  small / large / custom can be a thing though :P  Not usual on the web to have 2 fixed values and then the ability to go custom..  I played around w/ the UX using developer tools and it kinda made sense to be able to drag the webrtc entire window to be bigger/smaller..  Video UX in general is an interesting challenge IMHO.  If you have 20 people on a pad you might want the ability to "pin" a few people to the top of the window, for example!  Defo bike shedding but right now let's do granular baby steps as to not get overloaded.
