### ISSUE TITLE
Custom Video Size - Draggable

### ISSUE THREAD

**Issue by packardone** [ether/ep_webrtc#58]
Referencing the work that began in https://github.com/ether/ep_webrtc/issues/52 (and the embedded comments in that thread):

There needs to be a way whether users can manually enlarge the video to whatever size they need.  The problem is for users who are using sign language.  That subset of users need to be able to make the video quite large, without impacting the "large" setting used by everyone else.

Perhaps an one solution to this would be to add a way to pop-out the video--so that individual video windows could be resized by resizing the pop-out browser window.  Another option would be to allow the video corners to be draggable up to a specific maximum.

**Comment by orblivion** [comment]
@JohnMcLear I had a heck of a time figuring out plain htm/javascript dragging on the various browsers I'm trying it on. Getting the x/y coordinates _while dragging_ seems to not be supported.

It looks like there's dragging functionality built into jquery-ui. I'm wondering if it would be worth taking the time to try the same thing with that. It depends if you're inclined to add another dependency?

**Comment by JohnMcLear** [comment]
ugh really?  That's horrible..  I thought canvas elements supported native resize: https://konvajs.org/docs/sandbox/Image_Resize.html

**Comment by orblivion** [comment]
>  I think you only need a draggable element on bottom right.

Yep. I'll give Interact a try.
