### ISSUE TITLE
Implement Screen Sharing as an Option

### ISSUE THREAD

**Issue by packardone** [ether/ep_webrtc#59]
The WebRTC-powered screen sharing option is pretty robust and quick.  One pretty cool implementation is available at https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/

It'd be great to have screensharing incorporated into the WebRTC module for Etherpad.  Users would benefit because they could use Etherpad even when the shared work wasn't text base--or when that work would benefit from text supplemented with other examples (like Mathmatica, for example).

I see this implemented first as an option--it'd need to be turned on or off by a URL string if at all possible so that account-level control could be implemented.  For example:

1. If the URL contains "ss=YES," then a button appears on the toolbar.  When clicked, the button attempts to use WebRTC to show the screen of the person who clicked it.  Before doing so, a confirmation would need to appear: "Are you sure that you want to share your screen?  All participants in this room will be able to see your entire desktop if you continue."

2. If confirmed, a screen sharing window opens.  I see this as covering the pad completely--like ep_draw.  If someone is sharing their screen, a message should appear on all pad users that reads something like, "XXX is sharing their screen.  Click the screen sharing icon to see their shared screen."

3. Here's the impossible part... only one user should be able to share a screen at a time.  That means there would have to be a way to stop the sharing so that another user could start it.

Of course, these are just my unfinished ideas, but it gives us a place to start.

**Comment by orblivion** [comment]
At the moment, it looks like firefox and IE both have a popup that that warns you and/or lets you choose exactly what you want to share. I think that's fine but just keep that in mind with the additional warning you're talking about. I'd worry that UI might change in the browsers that might make its warning go away after first permission granted, so your warning may be worth keeping around.

I feel like the "start sharing srceen" button should turn into "view shared screen" once someone else is sharing their screen.

**Comment by rhansen** [comment]
Fixed by PR #131.
