### ISSUE TITLE
button for turning the webrtc feature on/off

### ISSUE THREAD

**Issue by danionescu2007** [ether/ep_webrtc#72]
I looked up and down for a way to enable a button to turn on/off the webrtc feature provided by your awesome plugin. I could not find it. Could you please explain how to achieve it. Thank you very much.

**Comment by orblivion** [comment]
If I'm not misunderstanding your question, you want to click the "gear"
icon on the top-right of the page, which will show "Pad Settings" with
various options. The one you're looking for is "Enable Audio/Video Chat",
which should be there assuming ep_webrtc is correctly installed.

**Comment by danionescu2007** [comment]
Thank you for your quick response.
The webrtc feature works fine, if enabled from settings json:
![image](https://user-images.githubusercontent.com/4688610/94384169-94c3ce00-014a-11eb-9b0e-53526ca7c473.png)
However i don't have any gear in my toolbar, as you can see in the screenshot above.  Or should I add it from settings.json?
Thanks again.

**Comment by orblivion** [comment]
Hmm, I guess you have the more basic skin enabled. Maybe try the star
button?

Someone more familiar with this skin may chime in...

**Comment by danionescu2007** [comment]
what skin do you recomend. I can switch to it, nevertheless.

**Comment by orblivion** [comment]
No the star is the save button. What are those two blank buttons? The
tooltip for the one we want should say "Settings"

**Comment by orblivion** [comment]
"colibris":
https://github.com/ether/etherpad-lite/blob/develop/settings.json.template#L90

I think it's the default these days (as implied by the linked file). Do you
have a long-running installation of etherpad here?

**Comment by danionescu2007** [comment]
I had the `settings` button missing under the toolbar section in settings.json. As you suspected, I upgraded from 1.8.0 to 1.8.4, but I kept the settings.json file. Now I realize I have to sync the newly added settings. Thank you very much for your help. Really appreciate it.
