### ISSUE TITLE
settings.json ignored

### ISSUE THREAD

**Issue by pr4xx** [ether/ep_webrtc#73]
Whatever I put inside the settings.json file, it does not change any behaviour of the plugin. Right now I have this at the top of my settings.json file:

```javascript
{
  "ep_webrtc" : {
   "enabled": false,
    "audio" : {
        "disabled": "none"
    },
    "video" : {
        "disabled": "hard"
    }
},
  /*
   * Name your instance!
   */
  "title": "Etherpad",
```

But nevertheless the plugin still gets started with both audio and video.
Do I have to put the key into some deeper configuration key?

**Comment by JohnMcLear** [comment]
cc @orblivion

**Comment by orblivion** [comment]
My guess was going to be something about where within the file you put it,
but it works for me at the top of the file.

Did you make sure to restart the etherpad server after changing your
settings file? That's all I can really think of.

**Comment by rhansen** [comment]
Unable to reproduce. There have been some changes to settings processing recently, so if there was a problem it is likely fixed.
