### ISSUE TITLE
Video issue

### ISSUE THREAD

**Issue by tfasano1** [ether/ep_webrtc#80]
# Video Issue
- For me, If 2 people join a pad they can only see their own camera, the other person's camera is black. Similarly, audio is not being served.
## Recreating the issue
- I'm testing this by going to my etherpad website (on a VPS not localhost) on my laptop and opening a pad.
-  Like I said it sees my laptop camera and displays it correctly, but when I connect to the same pad on mobile only 1 video feed is displaying on each respective device, the other being blank/black.
- This is probably trivial but I'd appreciate that someone who knew more about webrtc could help troubleshoot. 
- I realize both these devices are on the same LAN would this have anything to do with it?

## What I've tried
- I saw port 10000 was occupied by an old docker container so I opened it

## Could this be a turn server issue?
- I have the coturn service running

**Comment by JohnMcLear** [comment]
Yea, something is really broken with this plugin and it needs fixing.  I'm aware of it and need to find time to fix it.  A quick win for you might be to install an older version of the plugin ;/

**Comment by tfasano1** [comment]
Thank you!

**Comment by tfasano1** [comment]
Anyone know of a stable version? I've tried a bunch and no luck.

**Comment by JohnMcLear** [comment]
it was stable before @orblivion did some work, so look for his commits and grab it from there.

**Comment by tfasano1** [comment]
Thanks
